-- MySQL Script generated by MySQL Workbench
-- 06/03/15 16:17:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema censo_nc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema censo_nc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `censo_nc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `censo_nc` ;

-- -----------------------------------------------------
-- Table `censo_nc`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`area` (
  `id_area` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_area`),
  UNIQUE INDEX `id_area_UNIQUE` (`id_area` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`colonia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`colonia` (
  `id_colonia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `id_area` INT NOT NULL,
  PRIMARY KEY (`id_colonia`),
  UNIQUE INDEX `id_colonia_UNIQUE` (`id_colonia` ASC),
  INDEX `fk_colonia_area1_idx` (`id_area` ASC),
  CONSTRAINT `fk_colonia_area1`
    FOREIGN KEY (`id_area`)
    REFERENCES `censo_nc`.`area` (`id_area`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`vivienda` (
  `id_vivienda` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `cant_familia` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `id_colonia` INT NOT NULL,
  PRIMARY KEY (`id_vivienda`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC),
  INDEX `fk_vivienda_colonia_idx` (`id_colonia` ASC),
  CONSTRAINT `fk_vivienda_colonia`
    FOREIGN KEY (`id_colonia`)
    REFERENCES `censo_nc`.`colonia` (`id_colonia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`situacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`situacion` (
  `id_situacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_situacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`riesgo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`riesgo` (
  `id_riesgo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_riesgo`),
  UNIQUE INDEX `id_riesgo_UNIQUE` (`id_riesgo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`mat_piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`mat_piso` (
  `id_matpiso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `mat_pisocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_matpiso`),
  UNIQUE INDEX `id_matpiso_UNIQUE` (`id_matpiso` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`mat_paredes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`mat_paredes` (
  `id_matparedes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_matparedes`),
  UNIQUE INDEX `id_matparedes_UNIQUE` (`id_matparedes` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`agua_gris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`agua_gris` (
  `id_aguagris` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aguagris`),
  UNIQUE INDEX `id_aguagris_UNIQUE` (`id_aguagris` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`agua_negra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`agua_negra` (
  `id_aguanegra` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aguanegra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`servicio_basico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`servicio_basico` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`tipo_letrina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`tipo_letrina` (
  `id_tipoletrina` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipoletrina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`abast_agua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`abast_agua` (
  `id_abastagua` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_abastagua`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`manejo_basura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`manejo_basura` (
  `id_manejobasura` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_manejobasura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`vectores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`vectores` (
  `id_vectores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_vectores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`mat_techo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`mat_techo` (
  `id_mattecho` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mattecho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`seguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`seguridad` (
  `id_seguridad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_seguridad`),
  UNIQUE INDEX `idseguridad_UNIQUE` (`id_seguridad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`tenencia_vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`tenencia_vivienda` (
  `id_tenencia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `id_tenencia_UNIQUE` (`id_tenencia` ASC),
  PRIMARY KEY (`id_tenencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`mascota` (
  `id_mascota` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_mascota`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`Familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`Familia` (
  `id_familia` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_familia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`tipo_familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`tipo_familia` (
  `id_tipofamilia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipofamilia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`patrimonio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`patrimonio` (
  `id_patrimonio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_patrimonio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`religion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`religion` (
  `in_religion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`in_religion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`Nacionalidad` (
  `id_nacionalidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_nacionalidad`),
  UNIQUE INDEX `id_nacionalidad_UNIQUE` (`id_nacionalidad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`ingreso_economico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`ingreso_economico` (
  `id_ingreso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ingreso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`parentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`parentesco` (
  `id_parentesco` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_parentesco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`enfermedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`enfermedad` (
  `id_enfermedad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_enfermedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`nivel_educativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`nivel_educativo` (
  `id_niveleducativo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_niveleducativo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`situacion_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`situacion_laboral` (
  `id_sitlaboral` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sitlaboral`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`discapacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`discapacidad` (
  `id_discapacidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_discapacidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`tipo_discapacidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`tipo_discapacidad` (
  `id_tipodisca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipodisca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `censo_nc`.`causa_disca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `censo_nc`.`causa_disca` (
  `id_causa` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_causa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
